[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn myproject.wsgi"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10